In [17]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
c = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
print(a)
print(b)

[1 2 3]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
print(a.size)
print(a.ndim)
print(a.shape)

3
1
(3,)


In [15]:
print(b.size)
print(b.ndim)
print(b.shape)

9
2
(3, 3)


In [18]:
print(c.ndim)

3


In [19]:
c.shape

(2, 2, 2)

In [21]:
c.reshape(2,4)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [22]:
A = np.array([1,0])
B = np.array([0,1])
C = A + B
C

array([1, 1])

In [23]:
A = np.array([2,3])
B = np.array([4,5])
F = A* B
F

array([ 8, 15])

In [24]:
A = np.array([[2,3]])
B = np.array([[4],[5]])
G = np.dot(A,B)
G

array([[23]])

In [25]:
A = np.array([2,6,8,7,3])
H = A + 4
H

array([ 6, 10, 12, 11,  7])

In [26]:
A = np.array([2,6,8,7,3])
meanA = A.mean()
maxA = A.max()

print(meanA)
print(maxA)
print(np.pi)

5.2
8
3.141592653589793
